"""把日志协议中的机器标识转换为面向人的简体中文显示文本。

日志事件名、字段名和枚举值仍以稳定英文标识写入 JSONL 与事件账本，避免破坏
检索、重放和跨版本兼容；只有控制台与 WebUI 的展示支路调用本模块。未知值原样
显示，保证新事件在补充翻译前也不会丢失诊断信息。
"""

from __future__ import annotations

from typing import Any, Dict


EVENT_LABELS: Dict[str, str] = {
    "trace": "运行追踪",
    "action_decision": "行动决策",
    "awareness_started": "感知服务已启动",
    "awareness_tick_failed": "感知轮询失败",
    "backend_starting": "后端正在启动",
    "backfill_done": "历史数据补全完成",
    "bootstrap_adopted_ts_version": "采用现有数据库版本",
    "bootstrap_fresh_database": "创建全新数据库",
    "bootstrap_meta_version_missing": "数据库版本信息缺失",
    "cancel_audio_failed": "取消语音失败",
    "chat_emoji_description_timeout": "聊天表情理解超时",
    "chat_emoji_source_failed": "读取聊天表情失败",
    "chat_emoji_too_large": "聊天表情文件过大",
    "chat_glance_description": "聊天画面理解完成",
    "chat_glance_empty": "聊天画面理解无结果",
    "chat_glance_timeout": "聊天画面理解超时",
    "chat_image_description": "聊天图片理解完成",
    "chat_image_description_failed": "聊天图片理解失败",
    "chat_image_description_timeout": "聊天图片理解超时",
    "chat_image_model_not_multimodal": "聊天图片模型不支持视觉",
    "chat_image_source_failed": "读取聊天图片失败",
    "chat_image_too_large": "聊天图片文件过大",
    "chat_tick_failed": "对话轮询失败",
    "config_prune_reverted": "废弃字段删除已回滚",
    "db_backup_created": "数据库备份已创建",
    "db_fresh_initialized": "数据库初始化完成",
    "db_migration_done": "数据库迁移完成",
    "db_migration_failed": "数据库迁移失败",
    "db_migration_start": "开始数据库迁移",
    "db_migration_step": "执行数据库迁移步骤",
    "db_ready": "数据库已就绪",
    "db_up_to_date": "数据库已是最新版本",
    "embed_batch_failed": "批量生成记忆向量失败",
    "embed_fact_failed": "事实向量生成失败",
    "embed_query_failed": "查询向量生成失败",
    "embedding_client_init_failed": "向量客户端初始化失败",
    "emoji_auto_register_changed": "表情包自动登记已更新",
    "emoji_auto_register_description_failed": "表情包自动描述失败",
    "emoji_auto_register_invalid": "跳过无效表情包",
    "emoji_directory_scanned": "表情包目录扫描完成",
    "emoji_embedding_failed": "表情包向量生成失败",
    "emoji_integrity_verified": "表情包完整性检查完成",
    "emoji_library_ready": "表情包库已就绪",
    "emoji_registered": "表情包已登记",
    "emoji_selected": "已选择表情包",
    "emoji_selection_missed": "表情包未命中库",
    "scene_observed": "已更新群里的情况",
    "emit_failed": "事件发送失败",
    "expression_select": "表达方式选择",
    "expression_select_failed": "表达方式选择失败",
    "foreground": "前台活动变化",
    "image_description": "图片理解",
    "interest": "兴趣度更新",
    "llm_chunk": "模型流式片段",
    "llm_error": "模型调用失败",
    "llm_final": "模型输出完成",
    "llm_init_failed": "模型初始化失败",
    "llm_ready": "模型已就绪",
    "llm_request": "请求模型",
    "llm_request_retry": "模型请求重试",
    "llm_slow": "模型响应缓慢",
    "fact_extract_disabled": "事实抽取未启用",
    "knowledge_learned": "学到新知识",
    "memory_extract": "记忆抽取完成",
    "memory_spread": "联想扩散",
    "memory_extract_failed": "记忆抽取失败",
    "memory_fact": "写入记忆",
    "memory_fact_dropped": "记忆归属不明已丢弃",
    "meta_schema_version_unparsable": "数据库版本无法解析",
    "model_all_failed": "全部候选模型均失败",
    "model_switch": "切换候选模型",
    "model_task_inherits_chat": "模型任务沿用聊天配置",
    "mood_delta": "心情变化",
    "observation": "旁听消息",
    "prompt_record": "调用记录",
    "prompt_record_failed": "调用记录写入失败",
    "outbound_delivered": "回复投递完成",
    "outbound_dropped": "出站消息已丢弃",
    "outbound_reply_empty": "回复内容为空",
    "pending_promise_restore_failed": "待办约定恢复失败",
    "persona_apply_turn_failed": "临时语调应用失败",
    "proactive_decision": "主动发言决策",
    "proactive_intent": "主动意图评估",
    "proactive_service_disabled": "主动感知服务未启用",
    "proactive_speak_failed": "主动发言失败",
    "promise_handler_missing": "约定处理器缺失",
    "promise_rejected_for_person": "约定人物归属不匹配",
    "profile_refresh_failed": "画像刷新失败",
    "profile_refreshed": "人物画像已刷新",
    "promise_stashed": "约定已登记",
    "prompt_override_ignored": "提示词覆盖已忽略",
    "provider_model_list_probe_failed": "模型列表探测失败",
    "render_action_decision_failed": "行动决策面板渲染失败",
    "render_observation_failed": "旁听消息渲染失败",
    "render_turn_error_failed": "失败轮次面板渲染失败",
    "render_turn_failed": "对话轮次面板渲染失败",
    "reply_gate": "回复门控判定",
    "schedule_init_failed": "日程服务初始化失败",
    "schedule_ready": "日程已就绪",
    "schedule_service_ready": "日程服务已就绪",
    "selftest_no_provider": "自检未配置模型服务",
    "service_start_failed": "服务启动失败",
    "service_started": "服务已启动",
    "service_starting": "服务正在启动",
    "service_stop_error": "服务停止失败",
    "service_stopped": "服务已停止",
    "service_stopping": "服务正在停止",
    "settings_config_saved": "设置已保存",
    "shadow_decision_failed": "影子决策失败",
    "sleep_eval_failed": "睡眠状态评估失败",
    "sleep_transition": "睡眠状态变化",
    "speak_audio_failed": "语音发送失败",
    # 阶段事件正常由 stageLabel 给出具体阶段名，这条只是 stageLabel 缺失时的兜底显示，
    # 避免控制台打出一个没有事件名的空行。
    "stage": "处理阶段",
    "stream_registry_ready": "会话归属表已就绪",
    "turn_action": "轮次动作规划",
    "turn_competition": "轮次竞争处理",
    "turn_failed": "对话轮次失败",
    "tts_failed": "语音合成失败",
    "tts_ready": "语音合成已就绪",
    "user_input": "收到用户消息",
    "vector_recall_enabled": "向量记忆召回已启用",
    "vector_recall_init_failed": "向量记忆召回初始化失败",
    "vision_call_failed": "视觉模型调用失败",
    "vision_glance": "视觉扫视",
    "vision_model_not_multimodal": "视觉模型不支持图片",
    "vision_model_ready": "视觉模型已就绪",
    "vision_service_disabled": "视觉服务未启用",
    "vision_service_ready": "视觉服务已就绪",
    "ws_auth_failed": "事件通道鉴权失败",
    "ws_client_invalid": "事件通道客户端无效",
    "ws_connected": "事件通道已连接",
    "ws_disconnected": "事件通道已断开",
    "ws_error": "事件通道异常",
    "ws_push_failed": "事件推送失败",
}

for _version in range(3, 12):
    EVENT_LABELS[f"v{_version}_to_v{_version + 1}_done"] = (
        f"数据库 v{_version}→v{_version + 1} 迁移完成"
    )
EVENT_LABELS.update({
    "v3_to_v4_retokenize_cues": "重新整理记忆线索分词",
    "v3_to_v4_retokenize_facts": "重新整理记忆事实分词",
})


FIELD_LABELS: Dict[str, str] = {
    "accepted": "已接收",
    "action": "动作",
    "activeSource": "生效来源",
    "activity": "活动类型",
    "added": "新增数量",
    "ageMs": "数据年龄",
    "agentScope": "决策模式",
    "allow": "允许执行",
    "app": "应用",
    "asleep": "已入睡",
    "assumed": "推定版本",
    "at": "时间",
    "atmosphere": "气氛",
    "attempt": "尝试次数",
    "availableActions": "可用动作",
    "backendPort": "后端端口",
    "backfilled": "补全数量",
    "blockedSource": "被拦来源",
    "botName": "机器人",
    "botNames": "机器人名称",
    "bodyChars": "正文字数",
    "bonds": "关系数量",
    "bytes": "字节数",
    "candidateCount": "候选数量",
    "candidates": "候选数量",
    "channel": "通道",
    "chars": "字符数",
    "client": "客户端",
    "content": "内容",
    "count": "数量",
    "cues": "线索数",
    "date": "日期",
    "decisionSource": "决策来源",
    "decision": "最终决策",
    "dest": "目标路径",
    "detail": "说明",
    "directory": "目录",
    "desktop_stream_id": "桌面会话编号",
    "discovered": "发现数量",
    "disposition": "门控结果",
    "drowsy": "正在犯困",
    "echo": "回执标识",
    "elapsedMs": "耗时",
    "emotion": "情绪",
    "energy": "精力变化",
    "energyPace": "精力变化档位",
    "mood": "心情",
    "moodPace": "心情变化档位",
    "error": "错误",
    "errorKind": "错误类型",
    "errorType": "错误类型",
    "enabled": "已启用",
    "eventStatus": "事件状态",
    "externalMessageId": "外部消息编号",
    "facts": "事实数",
    "failures": "连续失败",
    "failed": "失败数量",
    "failed_model": "失败模型",
    "failed_provider": "失败服务",
    "favor": "好感变化",
    # 兴趣增长的五个乘数与合成速率，来自 awareness.interest.InterestFactors.as_trace()。
    # 它们相乘得到每分钟兴趣增长量，是复盘「她为什么这时候想说话」的唯一依据。
    "fAbsence": "久未互动系数",
    "fActivity": "活动系数",
    "fEnergy": "精力系数",
    "fFavor": "好感系数",
    "fIgnored": "被冷落系数",
    "ratePerMinute": "每分钟增长",
    "file": "文件",
    "files": "文件",
    "fn": "迁移函数",
    "followUp": "跟进",
    "from_meta": "元数据版本",
    "from_version": "原版本",
    "gateDisposition": "门控结果",
    "gate": "门控信息",
    "gateReasonCodes": "门控理由",
    "groupId": "群编号",
    "habits": "表达习惯数量",
    "hash": "内容指纹",
    "hint": "提示",
    "id": "编号",
    "interest": "兴趣度",
    "intensity": "活动强度",
    "intentType": "意图类型",
    "inputs": "输入条件",
    "kept": "保留数量",
    "kind": "事件类型",
    "length": "回复篇幅",
    "lastSeq": "最后序号",
    "limit": "上限",
    "maxRepliesInWindow": "窗口回复上限",
    "maxTokens": "最大令牌数",
    "max_retries": "最大重试次数",
    "memoryKind": "记忆类型",
    "message": "消息",
    "messageId": "消息编号",
    "messages": "提示词消息",
    "messageWatermark": "消息水位",
    "mentionedMe": "提到机器人",
    "model": "模型",
    "modelName": "模型",
    "modelTask": "模型任务",
    "mode": "模式",
    "name": "名称",
    "nameMentioned": "叫到机器人名字",
    "naturalReplyElapsedMs": "自然接话间隔",
    "note": "说明",
    # 认知动作（recall / inspect / consult）检索回来的结果，会作为下一轮决策的输入。
    "observation": "观察结果",
    "owner_person_id": "主人编号",
    "path": "路径",
    "peer": "远端地址",
    "personId": "人物编号",
    "personKind": "人物类型",
    "platform": "平台",
    "plan": "计划",
    "pool": "候选池",
    "port": "端口",
    "postType": "上报类型",
    "probability": "概率",
    "process": "进程",
    "protocol": "协议",
    "promptHash": "提示词指纹",
    "promptId": "提示词模板",
    "provider": "模型服务",
    "providerName": "模型服务",
    "raw": "原始值",
    "reason": "原因",
    "reasonCodes": "决策理由",
    "reply": "回复内容",
    "reasoning": "模型思考",
    "renderParams": "渲染参数",
    "requestType": "请求类型",
    "remaining": "剩余数量",
    "removed": "移除数量",
    "repliesInWindow": "窗口内回复数",
    "result": "结果",
    "retryCount": "重试次数",
    # ReAct 回环里这是第几次认知往返；0 表示直接给出终局动作，没有先去检索。
    "roundIndex": "认知回合",
    "scene": "场景变化",
    "seconds": "秒数",
    "senderDisplayName": "发送者显示名",
    "senderExternalId": "发送者账号",
    "senderGroupCard": "发送者群名片",
    "senderLabel": "发送者",
    "senderNickname": "发送者昵称",
    "selfId": "机器人账号",
    "selfName": "机器人昵称",
    "silent": "静默场景",
    "skipped": "跳过数量",
    "snapshot": "快照",
    "snapshotPath": "快照路径",
    "snapshots": "快照数量",
    "source": "来源",
    "stage": "处理阶段",
    "stageLabel": "处理阶段",
    "start": "起始位置",
    "status": "状态",
    "statusLabel": "状态",
    "sleep": "睡眠状态",
    "snapshotId": "快照编号",
    "streamId": "会话编号",
    "streamName": "会话",
    "subject": "约定内容",
    "strategy": "策略",
    "streamExternalId": "会话外部编号",
    "streamKind": "会话类型",
    "tags": "标签",
    "targetId": "目标编号",
    "targetMessageIds": "目标消息",
    "task": "模型任务",
    "temperature": "生成温度",
    "text": "正文",
    "to_version": "目标版本",
    "tried": "已尝试数量",
    "topic": "话题",
    "total": "候选总数",
    "trigger": "触发来源",
    "turnId": "轮次",
    "userId": "用户编号",
    "version": "版本",
    "verified": "校验数量",
    "voice": "音色",
    "waitedSeconds": "等待秒数",
    "windowChanged": "窗口已切换",
    "latencyMs": "模型耗时",
    "emojiEmotions": "表情情绪",
    "expressionIntent": "表达意图",
}


VALUE_LABELS: Dict[str, str] = {
    "away": "暂时离开",
    "backfill": "历史补全",
    "browsing": "浏览网页",
    "busy": "忙碌",
    "brief": "简短",
    "cached": "使用缓存",
    "committed": "已决定执行",
    "contact": "联系人",
    "coding": "编写代码",
    "delivery_failed": "投递失败",
    "desktop": "桌面",
    "chat": "聊天",
    "direct": "私聊",
    "disabled": "未启用",
    "drop": "拦截",
    "empty": "无结果",
    "expire": "到期清理",
    "failed": "失败",
    "gate_dropped": "门控拦截",
    "group": "群聊",
    "files": "浏览文件",
    "flush": "批量写入",
    "gaming": "玩游戏",
    "idle": "空闲",
    "illegal_action": "动作不合法",
    "long": "详细",
    "light": "轻度活动",
    "model": "模型判定",
    "music": "听音乐",
    "none": "无",
    "ok": "成功",
    "owner": "主人",
    "other": "其他活动",
    "parse_error": "解析失败",
    "provider_error": "模型服务错误",
    "react": "发表情回应",
    "poke": "戳一戳",
    "speak": "主动起话头",
    "wait": "先等下文",
    "recall": "翻长期记忆",
    "inspect": "翻更早的聊天",
    "consult": "查知识资料",
    "cognitive_step": "先查了一下",
    "reply": "回复",
    "reading": "阅读",
    "silent": "保持沉默",
    "silent_by_choice": "主动选择沉默",
    "skipped": "已跳过",
    "stash": "暂存",
    "system": "系统",
    "timeout": "超时",
    "unknown": "未知错误",
    "user": "用户",
    "video": "观看视频",
    "work": "处理工作",
    "assistant": "机器人",
    "awake": "清醒",
    "billing": "余额不足",
    "attention_filtered": "未进入注意范围",
    "frequency_budget": "发言频率攒够候选",
    "frequency_wait": "发言频率未攒够",
    "low_necessity": "回复必要性不足",
    "reply_necessity": "回复必要性达线",
    "bot_sleeping": "机器人正在睡觉",
    "direct_question": "明确提问",
    "directly_addressed": "直接叫到机器人",
    "direct_poke": "被戳了一下",
    "emotional_support": "需要情绪支持",
    "pending_thread": "有没接完的话头",
    "can_add_value": "能补充有价值的内容",
    "relationship_impulse": "出于关系想接一句",
    "natural_reaction": "自然而然的反应",
    "natural_reply_window": "处于自然接话窗口",
    "no_new_value": "没有新的回复价值",
    "others_conversation": "他人之间的对话",
    "duplicate_response": "会与已有回复重复",
    "not_addressed": "没有在对她说",
    "attention_elsewhere": "注意力不在这里",
    "low_relevance": "与她关联太弱",
    "rate_limited": "触发频率限制",
    "topic_closed": "话题已经结束",
    "topic_continuation": "延续当前话题",
    "would_interrupt": "回复会打断交流",
    "unfinished_thought": "对方话还没说完",
    "thread_developing": "这件事还在往下走",
    "noticed_activity": "看到他们在聊的事",
    "remembered_something": "想起一件相关的事",
    "long_silence": "太久没说话了",
    "promise_due": "之前答应的事到点了",

    # 回复门控的三档处置（``agent.conversation_gate``）。drop 已在上方登记为「拦截」。
    "deliberate": "交给她定",
    "force": "必须回应",

    # DROP 理由码：确定的硬过滤，不承载「她大概不想说」。
    # 与 DELIBERATE 那组分开补是因为此前只登记了 DELIBERATE，控制台于是一半中文
    # 一半机器码（现场表现：「决策理由：name_mention、被戳了一下、ongoing_topic」）。
    "self_message": "她自己发的",
    "asleep": "已经睡了",
    "consumed": "这条已经处理过",
    "timeout_window": "超出超时窗",
    "message_type_disallowed": "这类消息被配置关掉了",

    # FORCE 理由码：用户直接找她，模型没有沉默选项。
    "at_mention_must_reply": "被 @ 且设了必回",
    "direct_conversation": "对方在直接跟她说话",
    "system_confirmation": "系统确认",

    # DELIBERATE 理由码里此前漏登记的几条。
    "name_mention": "叫到她名字",
    "direct_mention": "被 @ 了",
    "reply_to_bot": "回复了她的消息",
    "ongoing_topic": "她在参与的话题还在继续",
    "clear_question": "有人明确在问",
    "recognizable_target": "认得出在说谁",

    # 主动搭话的预算与场景决策理由（``awareness.budget``）。
    "hidden": "窗口没开着",
    "budget": "今天主动次数用完了",
    "scene-reserve": "留给场景的额度不够了",
    "deferred_to_trigger_mode": "交给扩展触发口径判断",

    # 主动意图类型（``awareness.intent.IntentType``）。
    "Idle": "闲着想说话",
    "Scene": "看到场景变化",
    "Plan": "日程到点",
    "Promise": "之前的约定",

    # 占用会话的驱动源与跟进触发来源。
    "proactive": "主动搭话",
    "direct_follow_up": "私聊跟进",
}


def event_label(event_name: str) -> str:
    """返回日志事件的中文显示名，未知事件保留原值。"""
    return EVENT_LABELS.get(event_name, event_name)


def field_label(field_name: str) -> str:
    """返回结构化字段的中文显示名，未知字段保留原值。"""
    return FIELD_LABELS.get(field_name, field_name)


def value_label(value: str) -> str:
    """返回常见协议枚举的中文显示名，普通正文不会被改写。"""
    return VALUE_LABELS.get(value, value)


def display_value(value: Any) -> str:
    """将结构化字段值转换为紧凑中文文本。

    :param value: 日志字段中的任意 JSON 兼容值。
    :return: 布尔值、空值、枚举、列表和字典的中文展示文本。
    :raises TypeError: 嵌套值无法 JSON 序列化时抛出，避免掩盖错误数据。
    """
    if value is None:
        return "—"
    if isinstance(value, bool):
        return "是" if value else "否"
    if isinstance(value, str):
        return value_label(value)
    if isinstance(value, list):
        return "、".join(display_value(item) for item in value) if value else "无"
    if isinstance(value, dict):
        return "，".join(
            f"{field_label(str(key))}：{display_value(item)}"
            for key, item in value.items()
        ) or "无"
    return str(value)


__all__ = [
    "EVENT_LABELS",
    "FIELD_LABELS",
    "VALUE_LABELS",
    "display_value",
    "event_label",
    "field_label",
    "value_label",
]
